name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                  go-version: "1.25.1"
            - run: go test ./...
            - run: |
                  GOOS=linux GOARCH=amd64 go build -o bin/vaultfactory-server-linux-amd64 ./cmd/server
                  GOOS=linux GOARCH=amd64 go build -o bin/vaultfactory-client-linux-amd64 ./cmd/client
                  GOOS=windows GOARCH=amd64 go build -o bin/vaultfactory-server-windows-amd64.exe ./cmd/server
                  GOOS=windows GOARCH=amd64 go build -o bin/vaultfactory-client-windows-amd64.exe ./cmd/client
                  GOOS=darwin GOARCH=amd64 go build -o bin/vaultfactory-server-darwin-amd64 ./cmd/server
                  GOOS=darwin GOARCH=amd64 go build -o bin/vaultfactory-client-darwin-amd64 ./cmd/client
                  GOOS=darwin GOARCH=arm64 go build -o bin/vaultfactory-server-darwin-arm64 ./cmd/server
                  GOOS=darwin GOARCH=arm64 go build -o bin/vaultfactory-client-darwin-arm64 ./cmd/client
            - uses: softprops/action-gh-release@v1
              with:
                  files: bin/*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
